WebLab13/Models/ErrorViewModel.cs
namespace WebLab13.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebLab13/Models/QuizQuestion.cs
namespace WebLab13.Models
{
    public class QuizQuestion
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public int CorrectAnswer { get; set; }
        public int UserAnswer { get; set; }
    }
}

WebLab13/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebLab13.Models;

namespace WebLab13.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebLab13/Controllers/MockupsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebLab13.Models;

namespace WebLab13.Controllers
{

    public class MockupsController : Controller
    {
        private readonly ILogger<MockupsController> _logger;

        public MockupsController(ILogger<MockupsController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebLab13/Controllers/QuizController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using WebLab13.Models;

namespace WebLab13.Controllers
{
    public class QuizController : Controller
    {
        private static List<QuizQuestion> _questions = new List<QuizQuestion>
    {
        new QuizQuestion { Id = 1, Question = "1 - 6 =", CorrectAnswer = -5 },
        new QuizQuestion { Id = 2, Question = "8 + 6 =", CorrectAnswer = 14 },
        new QuizQuestion { Id = 3, Question = "5 - 7 =", CorrectAnswer = -2 },
        new QuizQuestion { Id = 4, Question = "5 - 2 =", CorrectAnswer = 3 }
    };

        [HttpGet("Mockups/Quiz")]
        public IActionResult Quiz(int questionId = 1)
        {
            if (questionId <= _questions.Count)
            {
                var question = _questions[questionId - 1];
                return View("Question", question);
            }
            else
            {
                return Result();
            }
        }

        [HttpPost("Mockups/Quiz")]
        public IActionResult Quiz(int questionId, int userAnswer, bool finish = false)
        {

            if (userAnswer < int.MinValue || userAnswer > int.MaxValue)
            {
                ModelState.AddModelError("UserAnswer", "Please enter a valid number.");
                var question = _questions[questionId - 1];
                return View("Question", question); 
            }

            var questionToUpdate = _questions[questionId - 1];
            questionToUpdate.UserAnswer = userAnswer;

            if (finish) 
            {
                return Result();
            }
            else if (questionId < _questions.Count)
            {
                return RedirectToAction("Quiz", new { questionId = questionId + 1 });
            }
            else
            {
                return Result();
            }
        }

        public IActionResult Result()
        {
            int rightAnswers = 0;

            foreach (var question in _questions)
            {
                if (question.UserAnswer == question.CorrectAnswer)
                {
                    rightAnswers++;
                }
            }

            ViewBag.RightAnswers = rightAnswers;
            return View("Result", _questions);
        }

        public IActionResult Index()
        {
            return Result();
        }
    }
}

WebLab13/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>Home page</h1>
<ul>
    <li><a href="/Mockups">Mockups</a></li>
</ul>

WebLab13/Views/Mockups/Index.cshtml
@{
    ViewData["Title"] = "Hello Mockups";
}

<h1>Mockups</h1>
<ul>
    <li><a href="@Url.Action("Quiz", "Mockups")">Quiz</a></li>
    <li><a href="@Url.Action("Index", "Quiz")">QuizResult</a></li>
</ul>

WebLab13/Views/Quiz/Question.cshtml
@model QuizQuestion

@{
    ViewData["Title"] = "Hello Quiz";
}

<h1>Quiz</h1>

<form asp-action="Quiz" method="post">
    <input type="hidden" name="questionId" value="@Model.Id" />
    <label>@Model.Question</label>
    <div class="quiz-form">
        <input type="number" name="userAnswer" value="@Model.UserAnswer" required />
    </div>
    <div class="quiz-buttons">
        <button type="submit">Next</button>
        <button type="submit" name="finish" value="true">Finish</button>
    </div>
</form>

WebLab13/Views/Quiz/Result.cshtml
@model List<QuizQuestion>

@{
    ViewData["Title"] = "Hello Quiz";
}

<h1>Quiz results</h1>

<p>Right answers @ViewBag.RightAnswers out @Model.Count </p>

<ol>
    @for (int i = 0; i < Model.Count; i++)
    {
        <li>@Model[i].Question @Model[i].UserAnswer</li>
    }
</ol>

WebLab13/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Backend3</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav>
            <p>Backend3</p>
            <a href="@Url.Action("Index", "Home")">Home</a>
            <a href="@Url.Action("Index", "Mockups")">Mockups</a>
        </nav>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer>
        <div class="divider"></div>
        <div>
            <p>© 2019 - Backend3</p>
        </div>
    </footer>
</body>
</html>